# Generated by Django 5.1 on 2024-08-15 12:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Description', models.TextField(default='No Description Available', null=True)),
                ('Location', models.CharField(max_length=200)),
                ('Status', models.CharField(choices=[('Pending Query', 'Pending Query'), ('Addressed Query', 'Addressed Query'), ('Approved Query', 'Approved Query')], default='Pending Query', max_length=20)),
                ('Created', models.DateTimeField(db_default=datetime.datetime(2024, 8, 15, 17, 58, 27, 784124))),
                ('Posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
