# Generated by Django 5.1 on 2024-08-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='Status',
            field=models.CharField(choices=[('PeQ', 'Pending Query'), ('ApQ', 'Approved Query'), ('AdQ', 'Addressed Query')], default='PeQ', max_length=3),
        ),
    ]
